// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  campaign: dynamic(() => import("./Campaign")),
  contact: dynamic(() => import("./Contact")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  shorten_about: dynamic(() => import("./ShortenAbout")),
};
