// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blogs: dynamic(() => import("./Blogs")),
  campaign: dynamic(() => import("./Campaign")),
  contact: dynamic(() => import("./Contact")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  open_roles: dynamic(() => import("./OpenRoles")),
  shorten_about: dynamic(() => import("./ShortenAbout")),
};
